<div class="messageInfo<?=$this->message->getReaded() == 'n' ? ' notRead' : ' read'?>">
	<p><?=$this->message->getMessage()?></p>

	<div class="links">
		<p><a href="<?=$this->url(array('controller' => 'mails', 'action' => 'new', 'id' => $this->message->getUid()))?>">Reply to <?=$this->message->getLogin()?></a></p>
	</div>
	<p>At: <strong><?=$this->Date($this->message->getCreateTime())?></strong></p>
</div>