<?=$this->doctype(Zend_View_Helper_Doctype::XHTML1_TRANSITIONAL);?>
<html>
	<head>
		<?=$this->headTitle();?>
		<?=$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8');?>

		<?
		echo "\n" . $this
			->headLink()
			->appendStylesheet('/css/main.css')
			->appendStylesheet('/css/jquery.alerts.css');
		?>
		
		<?
		echo "\n" . $this
			->headScript()
			->appendFile('/js/jquery.js')
			->appendFile('/js/jquery.alerts.js')
			->appendFile('/js/jquery.hotkeys.js')
			->appendFile('/js/Paginator.js')
			->appendFile('/js/main.js');
		?>
		
		<script type="text/javascript">
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-20911959-2']);
			_gaq.push(['_trackPageview']);

			(function() {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();
		</script>
	</head>
	
	<body>
		<div id="mainWrapper">
			<div id="menu"><?=$this->partial('menu.php');?></div>
			
			<div id="notMenuWrapper">
				<div id="breadcrumbs"><?=$this->partial('breadcrumbs.php');?>&nbsp;</div>

				<div id="main">
					<div id="content"><?=$this->layout()->content?></div>
				</div>
			</div>
		</div>
	</body>
</html>